export const githubTools = [
  {
    name: 'fetch_file',
    purpose: 'Read a repository file.',
    access: 'read',
    riskLevel: 'low',
    requiredPermissions: ['repo:read'],
    requiresApproval: false,
    idempotent: true,
    audit: false,
    verificationStrategy: 'Return provider file content and SHA.',
  },
  {
    name: 'create_branch',
    purpose: 'Create a repository branch.',
    access: 'write',
    riskLevel: 'medium',
    requiredPermissions: ['repo:write'],
    requiresApproval: false,
    idempotent: false,
    audit: true,
    sideEffects: 'Creates persistent repository state.',
    retryPolicy: 'Check whether branch exists before retrying.',
    verificationStrategy: 'Fetch/list branch and confirm starting SHA.',
  },
  {
    name: 'update_file',
    purpose: 'Replace repository file contents.',
    access: 'write',
    riskLevel: 'medium',
    requiredPermissions: ['repo:write'],
    requiresApproval: true,
    idempotent: false,
    audit: true,
    sideEffects: 'Creates a commit and changes repository content.',
    retryPolicy: 'Do not retry blindly on unknown state; inspect file/commit first.',
    verificationStrategy: 'Fetch file and confirm expected blob/commit state.',
  },
  {
    name: 'create_pull_request',
    purpose: 'Open a pull request.',
    access: 'write',
    riskLevel: 'medium',
    requiredPermissions: ['repo:write'],
    requiresApproval: true,
    idempotent: false,
    audit: true,
    sideEffects: 'Creates externally visible repository workflow state.',
    retryPolicy: 'Search for equivalent open PR before retrying.',
    verificationStrategy: 'Fetch PR and confirm head/base/title.',
  },
  {
    name: 'merge_pull_request',
    purpose: 'Merge a pull request into its target branch.',
    access: 'destructive',
    riskLevel: 'high',
    requiredPermissions: ['repo:merge'],
    requiresApproval: true,
    idempotent: false,
    audit: true,
    sideEffects: 'Changes canonical repository history and target branch state.',
    retryPolicy: 'Never retry blindly; inspect PR merged state first.',
    verificationStrategy: 'Fetch PR and target branch; confirm merged commit.',
  },
];
