export const tradingViewTools = [
  {
    name: 'search_symbols',
    purpose: 'Resolve provider-qualified market symbols before research calls.',
    access: 'read',
    riskLevel: 'low',
    requiredPermissions: [],
    requiresApproval: false,
    idempotent: true,
    audit: false,
    verificationStrategy: 'Use returned provider-qualified symbol.',
  },
  {
    name: 'run_screener',
    purpose: 'Run a read-only market screener using provider-supported columns.',
    access: 'read',
    riskLevel: 'low',
    requiredPermissions: [],
    requiresApproval: false,
    idempotent: true,
    audit: false,
    verificationStrategy: 'Preserve provider result completeness/partial-state metadata.',
  },
  {
    name: 'create_watchlist',
    purpose: 'Create a user-owned TradingView watchlist.',
    access: 'write',
    riskLevel: 'medium',
    requiredPermissions: ['watchlist:write'],
    requiresApproval: false,
    idempotent: false,
    audit: true,
    sideEffects: 'Creates persistent provider-side user state.',
    retryPolicy: 'On unknown execution state, list watchlists before retrying.',
    verificationStrategy: 'Fetch or list watchlists and confirm the created resource.',
  },
  {
    name: 'create_alert',
    purpose: 'Create a user-owned TradingView price alert.',
    access: 'write',
    riskLevel: 'medium',
    requiredPermissions: ['alert:write'],
    requiresApproval: true,
    idempotent: false,
    audit: true,
    sideEffects: 'Creates a persistent provider-side notification rule.',
    retryPolicy: 'On unknown execution state, inspect alerts before retrying.',
    verificationStrategy: 'Fetch/list alerts and confirm exact symbol, condition, and threshold.',
  },
  {
    name: 'delete_alert',
    purpose: 'Delete a user-owned TradingView alert.',
    access: 'destructive',
    riskLevel: 'high',
    requiredPermissions: ['alert:delete'],
    requiresApproval: true,
    idempotent: false,
    audit: true,
    sideEffects: 'Removes persistent provider-side user state.',
    retryPolicy: 'Never blindly retry after timeout; verify current alert state first.',
    verificationStrategy: 'Confirm target alert is absent after deletion.',
  },
];
